% Extract Frequency Features from EEG Signals
%
% Generated by G. Alipoor (alipoor@hut.ac.ir)
%     Last Modifications: March, 16th 2022

function Features = ExtractEEGFeatures(Data, Frame_Length, ...
    DeltaFilt, DeltaRange, ThetaFilt, ThetaRange, AlphaFilt, AlphaRange, BetaFilt, BetaRange)
% Extracting frequency features from the input data samples

NumChannels = size(Data, 1);
NumFrames = floor(size(Data, 2)/Frame_Length);
Data = Data(:, 1:NumFrames*Frame_Length);
Features = zeros(4*NumChannels, NumFrames);

for i_Frame = 1:NumFrames
    CurFeatures = [];
    for i_Channels = 1:NumChannels
        CurFrame = Data(i_Channels, (i_Frame - 1)*Frame_Length + 1:i_Frame*Frame_Length);

        Delta = filter(DeltaFilt, CurFrame);
        Delta = mean(abs(Delta'))/diff(DeltaRange);
        Theta = filter(ThetaFilt, CurFrame);
        Theta = mean(abs(Theta'))/diff(ThetaRange);
        Alpha = filter(AlphaFilt, CurFrame);
        Alpha = mean(abs(Alpha'))/diff(AlphaRange);
        Beta   = filter(BetaFilt, CurFrame);
        Beta  = mean(abs(Beta'))/diff(BetaRange);

        CurFeatures = cat(1, CurFeatures, [Delta; Theta; Alpha; Beta]);
    end
    Features(:, i_Frame) = CurFeatures;
end
end
