function varargout = getarg(pin,pnames,dflts)

% getarg
%         Get Arguments
%    Generated by G. Alipoor
%    Last Modifications December, 9th 2008
%  
%     varargout = getarg(pin,pnames,dflts)
% 
%	getarg Process parameter name/value pairs for setting the arguments.
%	This function accepts a cell array pnames of valid parameter names, a
%   cell array dflts of default values for the parameters named in pnames, and
%   additional parameter name/value pairs.  Returns parameter values A,B,...
%   in the same order as the names in pnames.  Outputs corresponding to
%   entries in pnames that are not specified in the name/value pairs are
%   set to the corresponding value from dflts.
% 
%	The output is of length twice that of the input arguments pnames and dflt.
%   The output odd arguments are the parameter values corresponding to the
%   input parameters defined in the pnames input where the next parameter
%   indicates whether the parameter is set by the input argument varargin (1)
%   or put from the default values of dflt (0).
%   
%   This utility is used by other functions to set the necessary input
%   parameters.
% 

inlength = length(pin);
plength  = length(pnames);
if floor(inlength/2)~=inlength/2
    error('As input parameters are treated in pairs, thier number should be even')
end

for m = 1:plength
    varargout(m) = dflts(m); %#ok<*AGROW>
    for n = 1:2:inlength
        if strcmpi(pnames{m},pin{n})
            varargout(m) = pin(n + 1);
        end
    end
end
