function P = ProfileNormalize(P, dispWarning)
%
% ProfileNormalize    Normalize dictionary in a profile for the Kernel RLS-DLA
%
%    Pin:                Input profile, before normalization
%    Pout:              Output profile, after normalization
%    dispWarning : Print warnings if true and warning is appropriate, (default: false)
%
% ex:
% Pn = ProfileNormalize(P0, true);
% 
% Generated by Ghasem Alipoor (alipoor@hut.ac.ir) and Karl Skretting (karl.skretting@uis.no)
% Last modification: 5 August 2022
%

tooSmall = 0.0001;
tooLarge = 1/tooSmall;

if (nargin < 1)
    error('Must have at least 1 input argument, see help.');
end
if (nargin < 2)
    dispWarning = false;
end
%
% Don't worry about this:
% if ~P.isNormalization && dispWarning
%     fprintf('\nWarning:  Field P.isNormalization is false, normalize anyway.\n');
% end
% if strcmpi(P.KernelType, 'Gauss') && dispWarning
%     fprintf('\nWarning: Normalization in Gaussian kernel space may not be a good idea.\n');
%     fprintf('  All x in R^N gives k(x,x)=1.00, x1 --> phi1, x2 --> phi2, ...\n');
%     fprintf('  phi = 0.5*phi1 + 0.5*phi2  shoud have ||phi|| < 1.0 when phi1 ~= phi2, \n');
%     fprintf('  and there is no x corresponding to phi. \n');
%     fprintf('  If phi is a dictionary atom is it then a good idea to normalize it? \n');
% end

S = sqrt(diag(P.Psi));   % column vector size Qx1
if min(S) < tooSmall
    % hmm, this is not good
    if dispWarning
        fprintf('\nWARNING: %s min( S=sqrt(diag(P.Psi)) ) is very small.\n',mfilename());
    end
    S(S < tooSmall) = 1.0;
end
if max(S) > tooLarge
    % hmm, this is not good
    if dispWarning
        fprintf('\nWARNING: %s max( S=sqrt(diag(P.Psi)) ) is very large.\n',mfilename());
    end
    S(S > tooLarge) = 1.0;
end
G = 1./S;                % Qx1
if strcmpi(P.KernelType, 'Lin')
    P.D = P.D .* repmat(G',P.N,1);   % =  * diag(G)  QxQ
end
P.W = repmat(S,1,P.L) .* P.W;           % diag(S) * ..     QxQ   D*W  is as before.
P.U = repmat(G,1,P.L) .* P.U;           % diag(G) * ..
P.C = (G*G') .* P.C;                    % diag(G) * C * diag(G)
P.Psi = (G*G') .* P.Psi;
end
